### ISSUE TITLE
upgrade 1.9.1 to 2.0.5 or 2.0.6 conflicting signature

### ISSUE THREAD

**Issue by nicleo** [g4rb4g3/ABRPTransmitter#14]
upgrade from 1.9.1 to 2.0.5 or 2.0.6 results in error: conflicting signature.
![IMG_4412](https://user-images.githubusercontent.com/29352936/72018390-d4b6ee00-3267-11ea-9f7f-7b4d07cb18e7.JPG)

**Comment by g4rb4g3** [comment]
sorry for that, but i had to reinstall everything and i don't have a backup of the old keys.
to get rid of that you have to uninstall abrptransmitter and reinstall the latest version.
everything from 2.0.5 on will have the same signing keys again.

**Comment by nicleo** [comment]
ok, as I don't know anything about Android, How do I uninstall ABRP Transmitter?
(IONIQ Electric 2018)

**Comment by g4rb4g3** [comment]
Go to Android settings > apps and choose ABRPTransmitter there. Next press uninstall.
