### ISSUE TITLE
Choose different cars

### ISSUE THREAD

**Issue by Xnygra** [g4rb4g3/ABRPTransmitter#2]
Hi, 
Great work. As you say in documentations this is for Hyundai Ioniq EV but it should work equally well on the Hyundai Kona EV and the the Kia Niro EV, the only thing needed is a way to choose between the car models in the App menu. Is this something that you could add? It would be great for me who is driving a Niro EV.
 
{"Kia;Niro 39 kWh (beta)": "kia:niro:19:39:other"}, {"Kia;Niro 64 kWh": "kia:niro:19:64:other"}
{"Hyundai;Kona 39 kWh (beta)": "hyundai:kona:19:39:other"}, {"Hyundai;Kona 64 kWh": "hyundai:kona:19:64:other"}

Thank you, and great work :)

**Comment by g4rb4g3** [comment]
I'm not sure if that's all thats needed. Could you pull some files from your car and send them to me?
Required are com.lge.ivi.jar and com.lge.ivi.odex both should be located under /system/framework.

**Comment by SoWErA** [comment]
g4rb4g3 if you give me a guide on how I would be happy to send you the files from my Kia E-Niro.

**Comment by g4rb4g3** [comment]
I don't know how to start the engineering menu on those cars. But if you know it then look for ADB settings and enable "wireless adb". On the Ioniq it's called "ADB connect type" choose wireless there.
https://www.youtube.com/watch?v=_Ym1BLPJ_Kg

Install the Android SDK on your computer and follow this guide: https://developer.android.com/studio/command-line/adb#wireless
Once you've connected pull the com.lge.ivi.jar from /system/framework. https://developer.android.com/studio/command-line/adb#copyfiles

**Comment by g4rb4g3** [comment]
nothing new here....
