### ISSUE TITLE
Not Uploading any live data

### ISSUE THREAD

**Issue by KapUttyy** [g4rb4g3/ABRPTransmitter#23]
Yesterday I had the following issue with 3.0.2:
ABRP site loaded in No Map Mode as configured. After a few seconds it showed a "A new version was release, do you want to reload".
Clicking "Yes" reloaded the site in Map Mode and the same windows appeared again.

At the same time, ABRPTransmitter did not start uploading any live data. In Log Windows was only one entry that the service started successfully and at the status tab nothing happened.

I don't know if this coheres, but I thought it could help finding the bug.

If you have further questions, just ask. :-)

**Comment by g4rb4g3** [comment]
the the abrp website has nothing to do with sending the live data. maybe the abrp api was not reachable. had that myself a few days ago.
maybe you try the reload button in the app next time abrp shows a new release. then it should at least remain in nomap mode.
