### ISSUE TITLE
Zoom wheel

### ISSUE THREAD

**Issue by g4rb4g3** [g4rb4g3/ABRPTransmitter#24]
Use right knob on head unit for zooming in and out on the map.

**Comment by SamuelBrucksch** [comment]
Guess you would have to call javascript functions to call clickevent of '+' and '-' in gecko view. Can you register listeners that fire javascript on the currently loaded page? i guess then it is easy...

there are javaScript functions zoomIn() and zoomOut() that zoom, so you could just call them to zoom in and out from a javascript console. you can try it in your browser.

Following calls could be handy:
Center map on car: `centermode = false; toggleCenter()` (centermode needs to be false so it centers again, else it will just toggle on/off
Zoom in: `zoomIn()`
Zoom out: `zoomOut()`
Enable night mode: `nightmode= false;toggleNight()`
Enable day mode: `nightmode= true;toggleNight()`

**Comment by SamuelBrucksch** [comment]
How to inject Javascript:
https://stackoverflow.com/questions/57244592/how-to-inject-javascript-to-geckoview-on-android

So it actually should be possible to use the wheel know and others to interact with the map.

**Comment by g4rb4g3** [comment]
That way doesn't work. You have to write a web extension. Only problem is that v67 of geckoview doesn't seem to support them.... At least the guides I found don't match the functionality in geckoview v67.
https://mozilla.github.io/geckoview/consumer/docs/web-extensions
And newer geckoviews don't work anymore on Android 4.2...
When I tried v71 and v72 I got an verifyexception. But not only on the navi, also on an Android emulator.
I then tried to just send the keyevenz zoom in/out but that zooms the whole website.

**Comment by g4rb4g3** [comment]
v67 got only initial webextension support, almost nothing i need is working :(
https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/doc-files/CHANGELOG

**Comment by g4rb4g3** [comment]
resolved with cdfac4ee882b13f97d977df06bc9dfbcecb8db4b
