### ISSUE TITLE
Support offline mode

### ISSUE THREAD

**Issue by SamuelBrucksch** [g4rb4g3/ABRPTransmitter#25]
If there is no internet connection it should still be possible to at least show SoC and current position in no map mode.

Current findings:
There is a callback in the `getTelemetry` function that extracts the data and stores it internally and calls some functions to update the UI. It should be possible to call those functions directly to simulate incoming telemetry data from ABRP servers.

`displayCarTelemetry(soc, speed, ext_temp, power, car_model, res);` <- i guess this is for the live data screen but might have impacts on nomap mode as well. Needs to be investigated.
`setCarLocation(lat, lon, heading, location, utc * 1000);` <- i guess this stores lat/lon and centers map on location if enabled.

Still to be discussed:
When to set these values. Only if there is no connection? Or always and block abrp server instead after initial loading?

**Comment by SamuelBrucksch** [comment]
Looks like after `drawCarLocation` redrawing automatically is done, so the order would be to set the telemetry data and then call `drawCarLocation` to update everything.

**Comment by g4rb4g3** [comment]
I'm not sure this way is a good idea. Guess it would be better to talk to the abrp guys to implement a JavaScript function we can use to update the data offline. If we "hack" in a way we have to keep updating it whenever abrp changes something.

**Comment by g4rb4g3** [comment]
finished with 1fad72f25aae740104b4057e67293e4cec346600
