### ISSUE TITLE
Right knob for zoom doesn't work

### ISSUE THREAD

**Issue by ingepettersen** [g4rb4g3/ABRPTransmitter#29]
ABRPTransmitter v3.16.

Hyundai Ioniq (2018) with latest update:
Software: AE_EV.EUR.SOP.008.1.191209
Firmware: AE.EV.EUR,0.5.352.191031.MICOM

Zooming via right knob doesn't work. On the screen's right edgde there is a small bubble with a number in it. This is movable (up/down) via touch, but doesn't do anything. This bubble only appeared after installing ABRPTransmitter.

Other sideloaded apps: CtsTestStarter, Omni Swipe, IoniqInfo.

**Comment by g4rb4g3** [comment]
Fixed with 3.1.7.
https://github.com/g4rb4g3/ABRPTransmitter/releases/tag/3.1.7

**Comment by g4rb4g3** [comment]
btw. the bubble doesn't come from ABRPTransmitter.
