### ISSUE TITLE
Send data from "offline" session.

### ISSUE THREAD

**Issue by cmunk** [g4rb4g3/ABRPTransmitter#31]
Sometimes I forget to turn on the hotspot to give internet to the car. But it would be awesome for the app to send the logs to ABRP upon arrival home and it connects to the home network, so I still get my drive logged correctly. Is that possible? Or not something you can do on your end?

At the moment I just get a direct line from 'last known' location home when I've been offline.

Thanks for your awesome work!

**Comment by g4rb4g3** [comment]
The app doesn't save anything, it just tries to send actual data every few seconds. If that is not possible data will be lost.
I don't know what kind of hotspot you use but maybe this would be a nice option for you to make sure it's enabled while driving?
https://play.google.com/store/apps/details?id=com.hyundai.hotspot
I'm using it for a few.months already and it works great. It automatically enables the hotspot when the phone connects to the car with Bluetooth.

**Comment by cmunk** [comment]
Yeah, it's not so much an issue for myself, but more when my wife drives it. The idea of being able to backlog the data and send when possible 'made sense'. But yeah I might just need to get some hotspot set up permanently in the car :)

**Comment by cmunk** [comment]
Generally having an app to track trips is what I'm after -- preferably in the headunit. Ioniqinfo does this to some degree -- the German is just a bit hard for me and it's not quite clear to me how it works :)
