### ISSUE TITLE
Suggestion: Data upload to cloud

### ISSUE THREAD

**Issue by ChiefMac** [g4rb4g3/ABRPTransmitter#33]
I am brand new to GitHub and ABRPTransmitter, so bear with me. My request seems simple to me, but I don't know if it is.

Is it possible to upload the EV data, in particular, State of Charge, to the cloud, e.g. a Google Drive file, as well as to ABRP please? ABRP Transmitter already has this data and writes it to ABRP online, so can this be repeated but for another online server?

I use Tasker quite a bit and would love to be able to remotely read the SOC of the vehicle without needing to use an OBD reader. I appreciate that a mobile to provide the WiFi Access Point and internet link is still needed when not in the car.

Thanks for a great app by the way :)

**Comment by ChiefMac** [comment]
Sorry, just realised my request is not helpful, since I want to access SOC when the vehicle is charging, but OFF, so ABRP Transmitter won't be running anyway. Doh!

**Comment by g4rb4g3** [comment]
Yeah ABRP Transmitter can't do anything when the car is off. That's why I got myself an EVNotiPi.
I even made an app to save the GPS hat for the Pi, see EVNotiPiLocationProvider if you want to get one too and save some money.
