### ISSUE TITLE
getting this error while running app in android emulator

### ISSUE THREAD

**Issue by vkatoch2000** [g4rb4g3/ABRPTransmitter#35]
GeckoConsole: [JavaScript Error: "Error: No matching message handler" {file: "undefined" line: 0}]

transmit data is disable.
any clue, what is missing,?

**Comment by vkatoch2000** [comment]
Manisfest has this permission
  "permissions": [
    "tabs",
    "nativeMessaging",
    "geckoViewAddons",
    "*://abetterrouteplanner.com/classic/*"....

**Comment by vkatoch2000** [comment]
ABRP tabs showing white screen

**Comment by g4rb4g3** [comment]
I never ran this in an emulator. This has many dependencies to the Hyundai framework I wonder that it even starts on the emulator.
Usually I run into the white screen problem on my test unit when I forget to set the correct date and time. This causes problems on validating the SSL certificate of the ABRP website.
