### ISSUE TITLE
Is this still functional?

### ISSUE THREAD

**Issue by warksit** [g4rb4g3/ABRPTransmitter#37]
The instruction video on YouTube has been taken down. How do I go about installing this? Happy to write an instructions page for the wiki with updated info if I can get it working.

**Comment by lordzeroMS** [comment]
I guess, the issue is with the new software you can't enter the android menu that easy. 

In the old system you just had to go to the clock and type on a specific postion on all three types and enter the current time as password. But don't know for the new one if this is possible.

**Comment by lordzeroMS** [comment]
But to your question, the app is still working on my car.

**Comment by g4rb4g3** [comment]
Not sure what happened to the videos but the app should still work fine. Depending on your firmware version sharing to the built in navi app could be broken.

**Comment by warksit** [comment]
I don't know how to install either ABRP or this to my car
